FROM ghcr.io/kuaukutsu/php:8.2-cli as app_cli_build

FROM app_cli_build AS app_setup

# Arguments
ARG UID=10001
ARG WORKDIR="/src"

# Configure
COPY conf/php.ini /usr/local/etc/php/php.ini

COPY --from=composer:latest --link /usr/bin/composer /usr/bin/composer

RUN echo "# Adduser #" \
    && adduser -u $UID -G www-data -s /bin/sh -D developer www-data

RUN echo "# Create structure #" \
    && mkdir -p $WORKDIR \
    && chown -R $UID:www-data $WORKDIR

RUN echo "# mongodb #" \
    && install-php-extensions \
      sync \
      mongodb

FROM app_setup AS app_cli

USER $UID
WORKDIR $WORKDIR

FROM app_setup AS app_worker

USER $UID
WORKDIR $WORKDIR

CMD ["php", "./yii", "queue/listen"]

FROM app_setup AS app_devel

RUN echo "# xdebug #" \
    && install-php-extensions xdebug

USER $UID
WORKDIR $WORKDIR
